urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "workout"

urlpatterns = [
    url(r'^$', views.Index, name="index"),
    url(r'^edit_workout/(?P<pk>\d+)', views.EditWorkoutSummary, name="edit_workout_form"),
    url(r'^profile', views.EditProfile, name="edit_profile"),
    url(r'^add_workout/', views.AddWorkoutSummary, name="add_workout_form"),
    url(r'^api/delete_workout/(?P<pk>\d+)', views.DeleteWorkout, name="delete_workout"),
    url(r'^api/chart_data', views.ChartData, name="chart_data"),
    url(r'^api/export_data', views.ExportData, name="export_data"),
    url(r'^api/chart_summary', views.ChartSummary, name="chart_summary"),
    url(r'^api/strength_data', views.StrengthData, name="strength_data"),
    url(r'^api/breakdown', views.ExerciseBreakdown, name="chart_breakdown"),
    url(r'^api/details', views.WorkoutDetails, name="workout_details"),
    url(r'^api/exercise_detail/(?P<id>\d+)', views.ExerciseDetails, name="exercise_detail"),
    url(r'^api/strength_detail/', views.StrengthDetails, name="strength_detail"),
    url(r'^api/exercise_by_type/(?P<type>\d+)', views.ExerciseByType, name="exercise_by_type"),
    url(r'^api/exercise_by_group/(?P<type>\d+)/(?P<group>\d+)', views.ExerciseByGroup, name="exercise_by_group"),
    url(r'^api/weight', views.WeightDetails, name="weight_detail"),
    url(r'^api/get_weight', views.GetWeight, name="get_last_weight"),
    url(r'^api/add_weight', views.AddWeight, name="add_weight"),
    url(r'^api/delete_weight/(?P<pk>\d+)', views.DeleteWeight, name="delete_weight"),
    url(r'^api/history_by_exercise/(?P<pk>\d+)', views.HistoryByExercise, name="history_by_exercise"),
    url(r'^api/exercises_performed', views.ExercisesPerformed, name="exercises_by_date"),
    url(r'^api/add_exercise', views.AddExercise, name="add_exercise"),
]

templates/workouttracker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Workout Tracker</title>
    <link rel="stylesheet" href="{% static 'workouttracker/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'workouttracker/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'workouttracker/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'workouttracker/css/font-awesome-all.css' %}">
    <!--<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />-->
    <link rel="stylesheet" href="/static/admin/css/widgets.css">
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>

    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script type="text/javascript" src="/static/admin/js/inlines.js"></script>

    <style>
        .well {padding: 5px; margin-bottom: 8px;}
        .total_row { border-top: 2px solid gray; }
        .row_border { border-bottom: 1px groove #eee; font-size: 15px; font-weight: 500;}
        .row_top_border { border-top: 2px groove #eee; font-size: 15px; font-weight: 500;}
        .big { font-size: 26px; margin-top: 3px; padding-left: 5px; }
        .padded { padding: 5px; }
        .centered { left: 50%; transform: translateX(-50%); }
    </style>
    {% block styles %}
    {% endblock %}
</head>
<body>

{% block body %}
{% endblock %}

</body>
<script src="{% static 'workouttracker/js/jquery.min.js' %}"></script>
<script src="{% static 'workouttracker/js/jquery-ui.js' %}"></script>
<script src="{% static 'workouttracker/js/bootstrap.min.js' %}" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

{% block scripts %}
{% endblock %}
</html>

templates/workouttracker/confirmDeleteModal.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true" id="confirmDeleteModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="confirmDeleteModalText"></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="delete-yes" data-what="" data-val="" data-date="">Yes</button>
                <button type="button" class="btn btn-primary" id="delete-no">No</button>
            </div>
        </div>
    </div>
</div>

templates/workouttracker/confirmModal.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true" id="confirmModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="confirmModalText"></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="confirm-yes">Yes</button>
                <button type="button" class="btn btn-primary" id="confirm-no">No</button>
            </div>
        </div>
    </div>
</div>

templates/workouttracker/exerciseModal.html
<div class="modal fade modal-md centered" id="exerciseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="padding-top: 40px;">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exerciseModalTitle">Add Exercise</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body" id="exerciseModalBody">
            <form id="add_exercise_form" action="{% url 'workout:add_exercise' %}" method="POST" class="form form-horizontal">
                {% csrf_token %}
                <input type="hidden" id="target" name="target">
                <input type="hidden" id="exercise_type" name="type">
                <div class="form-group">
                    <label class="control-label col-sm-3" for="exercise_name">Name:</label>
                    <div class="col-sm-9">
                        <input type="text" name="name" id="exercise_name" class="form-control" required="required">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3" for="main_group">Main Group:</label>
                    <div class="col-sm-9">
                        <select name="main_group" id="main_group" class="form-control" required="required">
                            {% for group in all_groups %}
                                <option value="{{ group.id }}">{{ group.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12 text-right">
                        <button type="submit" class="btn btn-primary">Add Exercise</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/workouttracker/formModal.html
<div class="modal fade modal-lg centered" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="ModalLabel">Modal title</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body" id="ModalBody">
        </div>
        <div class="modal-footer" id="ModalFooter">
        </div>
    </div>
</div>

templates/workouttracker/index.html
{% extends 'base.html' %}
{% load dict_key %}
{% load index %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="form form-horizontal" id="controller">
                <div class="panel panel-default">

                    <div class="row" style="padding: 5px;">
                        <div class="col-sm-3 col-md-push-9 col-xs-12 icon_bar">
                            <a class="add_workout" title="Add workout"><i class="fas fa-plus-circle big"></i></a>
                            <a class="add_weight" title="Add weight"><i class="fas fa-weight big"></i></a>
                            <a class="edit_profile" title="Add weight"><i class="fas fa-user-circle big"></i></a>
                            <a class="export_data" title="Export Data"><i class="fas fa-file-export big"></i></a>
                        </div>

                        <div class="col-sm-1 col-md-pull-4"></div>
                        <label class="control-label col-sm-1 col-md-pull-3" for="start_date">Start:</label>
                        <div class="col-sm-3 col-md-pull-3">
                            <input class="form-control" id="start_date" name="start_date" type="date" value="{{ start_date }}">
                        </div>

                        <label class="control-label col-sm-1 col-md-pull-3" for="end_date">End:</label>
                        <div class="col-sm-3 col-md-pull-3">
                            <input class="form-control" id="end_date" name="end_date" type="date" value="{{ end_date }}">
                        </div>




                    </div>
                    <div class="row" style="padding: 5px;">
                        <div class="col-sm-1"></div>
                        <!--<div class="col-sm-2 text-center"><button type="button" data-val="7" id="week_button" class="btn btn-secondary btn-block date-filter-button">Week</button></div>-->
                        <div class="col-sm-2 text-center hidden-sm hidden-xs"><button type="button" data-val="30" id="month_button" class="btn btn-success btn-block active date-filter-button">Month</button></div>
                        <div class="col-sm-2 text-center hidden-sm hidden-xs"><button type="button" data-val="365" id="year_button" class="btn btn-secondary btn-block date-filter-button">Year</button></div>

                        <label class="control-label col-sm-1" for="chart">View:</label>
                        <div class="col-sm-3">
                            <select class="form-control" id="chart" name="chart">
                                <option value="summary">Summary</option>
                                <option value="breakdown">Breakdown by Group</option>
                                <!--<option value="totals">Workout Summary</option>-->
                                <option value="details">Workout Details</option>
                                <option value="strength">Strength Training</option>
                                <option value="by_exercise">History by Exercise</option>
                                <option value="weight">Weight History</option>
                            </select>
                        </div>

                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-block btn-action btn-sm">Update</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row strength-drill-down" style="display: none;">
        <div class="col-sm-12">
            <form class="form form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-xs-2">Group:</label>
                    <div class="col-sm-4 col-xs-4">
                        <select name="group" id="strength-group" class="form-control">
                            <option value="">-- All --</option>
                            {% for group in groups %}
                                <option value="{{ group.name }}">{{ group.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <label class="control-label col-sm-1 col-xs-1">By:</label>
                    <div class="col-sm-4 col-xs-4">
                        <select name="group" id="strength-unit-group" class="form-control">
                            <option value="weight">Weight</option>
                            <option value="reps">Sets/Reps</option>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row exercise_selection" style="display: none;">
        <div class="col-sm-12">
            <form class="form form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-2">Select Exercise:</label>
                    <div class="col-sm-4">
                        <select name="group" id="select_exercise" class="form-control">
                        </select>
                    </div>
                    <label class="control-label col-sm-1">By:</label>
                    <div class="col-sm-4">
                        <select name="group" id="exercise_history_by" class="form-control">
                            <option value="weight">Weight</option>
                            <option value="reps">Sets/Reps</option>
                            <option value="time">Time</option>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row chart_container" id="charts" style="display: block;">
        <div class="col-md-12 chart_container">
            <div id="summary_chart" class="chart_container" style="display: block;">
                <canvas id="myChart" class="chart_container" width="400" height="250"></canvas>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12"><hr></div>
    </div>
    <div class="row" id="details" style="display: none;">
    </div>
</div>

{% include 'workouttracker/formModal.html' %}
{% include 'workouttracker/exerciseModal.html' %}
{% include 'workouttracker/confirmModal.html' %}
{% include 'workouttracker/confirmDeleteModal.html' %}
{% include 'workouttracker/weightModal.html' %}
{% include 'workouttracker/waitModal.html' %}
{% include 'workouttracker/loadingModal.html' %}
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
<script src="{% static 'workouttracker/js/scripts.js' %}"></script>
{% if not has_profile %}
<script>
    $(".edit_profile").trigger("click");
</script>
{% endif %}
{% endblock %}

templates/workouttracker/loadingModal.html
<div id="loadingModal" class="modal" style="position: absolute; top: 200px;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span class="glyphicon glyphicon-time"></span> &nbsp;Please wait...</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-info progress-bar-striped active" style="width: 100%"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/workouttracker/profileForm.html
{% load index %}
{% load static %}

{% block body %}
{% if msg %}
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-danger" role="alert">
                {{ msg }}
            </div>
        </div>
    </div>
{% endif %}
<form action="{% url 'workout:edit_profile' %}" method="post" id="profile_form" class="form form-horizontal">
    {% csrf_token %}
    <div class="row">
        {% for field in user_form %}
            <div class="col-sm-2 padded">
                {{ field.label_tag }}
            </div>
            <div class="col-sm-4 padded">
                {{ field }}
            </div>
        {% endfor %}

        {% for field in profile_form %}
            <div class="col-sm-2 padded">
                {{ field.label_tag }}
            </div>
            <div class="col-sm-4 padded">
                {{ field }}
            </div>
        {% endfor %}
    </div>

    <div class="row">
       <div class="col-sm-12 text-right">
           <button type="submit" class="btn btn-primary" name="save_btn" value="continue">Save</button>
           <button type="button" class="btn btn-secondary" id="close_profile_form" data-val="{{ date }}">Close</button>
       </div>
    </div>
</form>

<script>
    {% if user.workout_user.unit_type == "imp" %}
        // update the range on the height input
        $("#id_profile-height").attr("min", 48);
        $("#id_profile-height").attr("max", 96);
    {% endif %}

    $("#id_profile-unit_type").on("change", function(e){
        units = $(this).val();
        if(units == "imp"){
            // update the label
            $("#profile_height_units").html("(in)");
            // update the range
            $("#id_profile-height").attr("min", 48);
            $("#id_profile-height").attr("max", 96);
        } else {
            $("#profile_height_units").html("(cm)");
            $("#id_profile-height").attr("min", 120);
            $("#id_profile-height").attr("max", 213);
        }
    });
</script>
{% endblock %}

templates/workouttracker/waitModal.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true" id="waitModal">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Exporting Data</h4>
            </div>
            <div class="modal-body" id="WaitModalBody">
                Please wait...
            </div>
        </div>
    </div>
</div>

templates/workouttracker/weightModal.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true" id="weightModal">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="weightHeader">Enter your weight:</h4>
            </div>
            <form class="form form-horizontal" id="weight_form" action="{% url 'workout:add_weight'%}" method="post">
                {% csrf_token %}
                <input type="hidden" id="weight_id" name="id" value="">
                <div class="modal-body" id="WeightModalBody">
                    <p id="previous_weight">Your last recorded weight was <span id="last_weight"></span> <span id="weight_units">kg</span> on <span id="last_weight_date"></span>.</p>

                    <div class="row" style="padding-top: 5px;">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="weight" class="col-sm-2">Date:</label>
                                <div class="col-sm-4">
                                    <input type="date" class="form-control" required="true" name="date" id="date" value="{% now 'Y-m-d' %}">
                                    <div class="error text-danger" style="display: none;" id="date_error">
                                        <p>Please enter a valid date!</p>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="weight" class="col-sm-2">Weight:</label>
                                <div class="col-sm-4">
                                    <input type="number" step="any" class="form-control" required="true" name="weight" id="weight">
                                    <div class="error text-danger" style="display: none;" id="weight_error">
                                        <p>Please enter a valid weight!</p>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    {% if profile.unit_type == 'imp' %}
                                        lbs
                                    {% else %}
                                        kg
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="bodyfat" class="col-sm-2">Body Fat:</label>
                                <div class="col-sm-4">
                                    <input type="number" step="any" class="form-control" name="bodyfat" id="bodyfat">
                                    <div class="error text-danger" style="display: none;" id="bodyfat_error">
                                        <p>Please enter a valid body fat!</p>
                                    </div>
                                </div>
                                <div class="col-sm-3">%</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" id="close_weight" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="add_weight">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/workouttracker/workout_form.html
{% load index %}
{% load static %}

{% block body %}
    {% if workout.id %}
        <form action="{% url 'workout:edit_workout_form' workout.id %}" id="edit_workout_form" method="post">
    {% else %}
        <form action="{% url 'workout:add_workout_form' %}" id="add_workout_form" method="post">
    {% endif %}
        {% csrf_token %}
        <input type="hidden" name="saved" id="saved" value="0">
        <div class="row" style="padding: 5px;">
            {% for field in form %}
                {% if field.name == "time" %}
                    <div class="col-sm-2 padded">
                        {{ field.label_tag }}
                    </div>
                    <div class="col-sm-3 padded">
                         {{ field }}
                    </div>
                    <div class="col-sm-1 padded">
                        <a class="time_now">Now</a>
                    </div>
                {% elif field.name != 'notes' %}
                    <div class="col-sm-2 padded">
                        {{ field.label_tag }}
                    </div>
                    <div class="col-sm-4 padded">
                         {{ field }}
                    </div>
                {% else %}
                    </div>
                    <div class="row" style="padding: 5px;">
                        <div class="col-sm-2 padded">
                            {{ field.label_tag }}
                        </div>
                        <div class="col-sm-10 padded">
                             {{ field }}
                        </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-sm-12">
               <hr>
            </div>
        </div>
        {{ exercise_form.management_form }}
        <div class="exercise_detail_form" {% if not workout.id %}style="display: none;"{% endif %}>
            <div class="row small_display">
                <div class="col-md-12"><h4>Exercises:</h4></div>
            </div>
            <div class="row large_display">
                <div class="col-sm-3">
                    <label for="exercise">Exercise:</label>
                </div>
                <div class="col-sm-1 strength_field">
                    <label for="sets">Sets:</label>
                </div>
                <div class="col-sm-1 strength_field">
                    <label for="reps">Reps:</label>
                </div>
                <div class="col-sm-2 strength_field">
                    <label for="weight">Weight ({% if profile.unit_type == 'imp' %}lbs{% else %}kg{% endif %}):</label>
                </div>
                <div class="col-sm-2">
                    <label for="intensity">Intensity:</label>
                </div>
                <div class="col-sm-2">
                    <label for="duration">Duration:</label>
                </div>
                <div class="col-sm-2 walk_field">
                    <label for="distance">Distance ({% if profile.unit_type == 'imp' %}mi{% else %}km{% endif %}):</label>
                </div>
                <div class="col-sm-1">
                    <label for="delete">Delete:</label>
                </div>
            </div>
            {% for form in exercise_form %}
                <div class="row" style="padding: 5px;">
                    {% for field in form %}
                        {% if field.name == "exercise" %}
                            <div class="col-sm-3">
                                <label class="control-label small_display">Exercise: </label>
                                {{ field }}
                                <img src="/static/admin/img/icon-addlink.svg" alt="Add" class="add_exercise" data-target="{{ field.auto_id }}">
                            </div>
                        {% elif field.name == "intensity" %}
                             <div class="col-sm-2">
                                 <label class="control-label small_display">Intensity: </label>
                                {{ field }}
                            </div>
                        {% elif  field.name == "distance" %}
                             <div class="col-sm-2 walk_field">
                                 <label class="control-label small_display">Distance: </label>
                                {{ field }}
                            </div>
                        {% elif field.name == "duration"  %}
                            <div class="col-sm-2">
                                <label class="control-label small_display">Duration: </label>
                                {{ field }}
                            </div>
                        {% elif field.name == "id" %}
                            {{ field }}
                        {% elif field.name == "DELETE" %}
                            <div class="col-sm-1 text-left">
                                <label class="control-label small_display">{{ field.label }}: </label>
                                {{ field }}
                            </div>
                        {% elif field.name == "reps" or field.name == "sets" %}
                            <div class="col-sm-1 strength_field">
                                <label class="control-label small_display">{{ field.label }}: </label>
                                {{ field }}
                            </div>
                        {% elif field.name == "weight"  %}
                            <div class="col-sm-2 strength_field">
                                <label class="control-label small_display">{{ field.label }}: </label>
                                {{ field }}
                            </div>
                        {% else %}
                            <div class="col-sm-1">
                                {{ field }}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="col-xs-12 small_display"><hr></div>
                </div>
            {% endfor %}
        </div>

        <div class="row">
           <div class="col-sm-12 text-right">
               <button type="submit" class="btn btn-primary" name="save_btn" value="continue">Save</button>
               <button type="button" class="btn btn-secondary close_form" id="close_form" data-val="{{ date }}">Close</button>
           </div>
        </div>
    </form>

    <script>
        {% if workout.id or edit %}
            $("#id_summary-type").trigger("change");
            $("#id_summary-time").val("{{time}}");

            // handle the conversion from metric if neccessary
            {% if profile.unit_type == "imp" %}
                convert_weights();
            {% endif %}
        {% endif %}
        {% if workout.group_id %}
            $("#id_summary-group").trigger("change");
        {% endif %}
    </script>
{% endblock %}

{% block styles %}
{%endblock %}